Eteryu:
    name:
    description: "Piszę o cyfrowej suwerenności, prywatności i bezpieczeństwie."
    avatar: https://raw.githubusercontent.com/Eteryu404/docs.eteryu.space/refs/heads/main/docs/assets/img/1552167043208769.png
